<a href="https://colab.research.google.com/github/Kishan-kp-ai/Linkific-Tasks/blob/main/Day%204/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr);



[1 2 3 4]


In [11]:
arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [12]:
print(arr2[1, 1])

50


In [13]:
print(arr2[2, 0])


70


In [14]:
print(arr2[0:2])

[[10 20 30]
 [40 50 60]]


In [15]:
print(arr2[:, 1])

[20 50 80]


In [16]:
arr = np.array([10, 20, 30, 40, 50])

In [21]:
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

150
30.0
50
10
